### ISSUE TITLE
paths to dependencies in Cargo.toml reflect setup on local machine

### ISSUE THREAD

**Issue by ramin** [bennyhodl/dlcdevkit#14]
When setting this up to see if i could make a contribution, i noticed a few entries in `ddk/Cargo.toml` reference local dependencies https://github.com/bennyhodl/dlcdevkit/blob/master/ddk/Cargo.toml#L19

eg:

```
dlc = { version = "0.6.0", path = "/Users/ben/ernest/dev/libs/rust-dlc/master/dlc", features = ["use-serde"] }
dlc-manager = { version = "0.6.0", path = "/Users/ben/ernest/dev/libs/rust-dlc/master/dlc-manager", features = ["use-serde"] }
dlc-messages = { version = "0.6.0", path = "/Users/ben/ernest/dev/libs/rust-dlc/master/dlc-messages", features = [ "use-serde"] }
dlc-trie = { version = "0.6.0", path = "/Users/ben/ernest/dev/libs/rust-dlc/master/dlc-trie", features = ["use-serde"] }
```

I'd like to propose we create a .gitignored directory in the project (`libs`) that has said dependies referenced and we update the Justfile to pull these from the proper git sha (i assume 0.6.0 of these is a pre-release?)

Then we can replicate this setup in a CI step i was planning to build?

Thoughts?

**Comment by EvanWinget** [comment]
I'm supportive of moving these to gitignore and pulling down via Just - same pattern is seen in /payouts/cargo.toml and in mprocs.yaml

I've been playing around trying to get a local example running and haven't been able to do it successfully yet

**Comment by bennyhodl** [comment]
> I'd like to propose we create a .gitignored directory in the project (`libs`) that has said dependies referenced and we update the Justfile to pull these from the proper git sha (i assume 0.6.0 of these is a pre-release?)

That's a great I idea.

Ya, making a big upgrade for `bitcoin@32.0` [pr here to rust-dlc](https://github.com/p2pderivatives/rust-dlc/pull/234)
