### ISSUE TITLE
Website down (https://dlcdevkit.com/)

### ISSUE THREAD

**Issue by Arvin21M** [bennyhodl/dlcdevkit#61]
Connection timeout

![image](https://github.com/user-attachments/assets/ab245de8-aa2b-4248-a0a8-5d8f8d45607a)

![image](https://github.com/user-attachments/assets/5d7c8b84-ec5c-42a4-bed3-a95e44e03770)

**Comment by bennyhodl** [comment]
thanks, tracked down DNS issues working now,

https://dlcdevkit.com
